// <auto-generated />
using lunchPollNet.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace lunchPollNet.Migrations
{
    [DbContext(typeof(PollContext))]
    [Migration("20171023104104_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("lunchPollNet.Models.Poll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ClosingTime");

                    b.Property<DateTime>("Created");

                    b.HasKey("Id");

                    b.ToTable("Poll");
                });

            modelBuilder.Entity("lunchPollNet.Models.PollItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<Guid>("PollId");

                    b.Property<Guid>("RestaurantId");

                    b.Property<int>("TotalVoteCount");

                    b.Property<bool>("disabled");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("PollItem");
                });

            modelBuilder.Entity("lunchPollNet.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("LunchUrl");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PostalCode")
                        .IsRequired();

                    b.Property<string>("StreetAddress")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Restaurant");
                });

            modelBuilder.Entity("lunchPollNet.Models.PollItem", b =>
                {
                    b.HasOne("lunchPollNet.Models.Poll", "Poll")
                        .WithMany("PollItems")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("lunchPollNet.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
